name: Android CI Build and Sign

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Signing Environment Variables
        run: |
          echo "${{ secrets.SIGNING_KEYSTORE_BASE64 }}" | base64 --decode > release-key.jks
          
          echo "KEYSTORE_FILE=$PWD/release-key.jks" >> $GITHUB_ENV
          echo "KEYSTORE_PASSWORD=${{ secrets.SIGNING_STORE_PASSWORD }}" >> $GITHUB_ENV
          echo "KEY_ALIAS=${{ secrets.SIGNING_KEY_ALIAS }}" >> $GITHUB_ENV
          echo "KEY_PASSWORD=${{ secrets.SIGNING_KEY_PASSWORD }}" >> $GITHUB_ENV

      - name: Debug Passwords Length
        run: |
          echo "Debugging Secret Lengths (Do not expose values):"
          STORE_PASS_LEN=${#STORE_PASS}
          echo "Store Password Length: $STORE_PASS_LEN"
          KEY_PASS_LEN=${#KEY_PASS}
          echo "Key Password Length: $KEY_PASS_LEN"
          if [[ $STORE_PASS_LEN -eq 0 ]]; then
            echo "ERROR: SIGNING_STORE_PASSWORD is empty or not loaded!"
            exit 1 # Bricht den Build ab, um den Fehler zu erzwingen
          fi
        env:
          KEYSTORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}

      - name: Build Signed AAB
        run: ./gradlew :app:bundleRelease
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pucktual-release
          path: app/build/outputs/bundle/release/app-release.aab
          retention-days: 7
